# Generated by Django 3.2 on 2021-08-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0019_auto_20210809_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
