# Generated by Django 3.2 on 2021-08-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0021_auto_20210810_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Colors'},
        ),
        migrations.AddField(
            model_name='product',
            name='tag_color',
            field=models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
