# Generated by Django 3.2 on 2021-08-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0022_auto_20210810_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
