# Generated by Django 2.2.14 on 2022-11-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0033_auto_20221120_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
    ]
