# Generated by Django 2.2.14 on 2022-11-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0036_auto_20221121_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleproduct',
            name='category',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
