# Generated by Django 2.2.14 on 2022-11-21 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0037_auto_20221121_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleproduct',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='saler.category', verbose_name='Category'),
        ),
    ]
