# Generated by Django 2.2.14 on 2022-11-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0038_auto_20221121_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='TotalCal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='TotalTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='URL',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='diet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
